sudo: required
dist: trusty
language: node_js
node_js:
  - '8.1.2'
  - 'stable'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome

    packages:
      - google-chrome-stable
      - g++-4.8
  firefox: 'latest'
cache:
  directories:
    - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: c2ialXOj9dCoh7LYpO8HKyjgjoYR6qLvXGQMbrQ3QSoJpbDr45p6Qn+SxYdji+s1248t471x32iIvo7XA01tb64hCQ/iZ7F6t+nFuEMilAGqczDebghpJEFtJ0sfIi1Imt/+GinlUF2Xv5NMJ8mL/mv4w3xsTpYTCGm+tnc8/D3DoUEew58EsJNZtA97dpztIDLWDBKb2Dl1gyy6kozn72Nxlr2M0XK6lHhiNccYV3LlTyKeQ17JWJtkZVEzDCjVnTnjvZZx1XiF2UQ5w9sD2BDI/Q06FaYvmCsZSWfbwDN8lHrYw2GCnadYeGiOdBiU6C4Hb0UQ99ku9oBwBympsTUygWvP80w5tqkeoo0d6tMR6ETlGocYeDYsVN5qGB0xz6j8fUEtt5OENsYJvoeHLQsxrAP4PbzPcg6mLkVoUs39SGlyqyQTbgTWPmpQWkbPTkTPwOqQw3TLd2qX75stFRIc9UynuKqTLgsOMmvWpPkYaRZa7yEyCWHX9VuRo+clBLvib9aqBKAIukK36hRCqBTO3Gk2qFM1FFF7d/LkOLSUBVXQ8ear+twby7Qm/b+YiETP16lVC2IfwfgZx1pLU4P/Jm3lmHof2vPbX95Yblpv6SnQmXPyN8S2BICBliMusUrcX5x4WdZBceRVvh2lcOIcU8qIucHcAn4SIqFrH20=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary
  - node_js: 'stable'

before_install:
  - npm config set spin false
  - npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh
install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - .travis/maybe-bump-version.sh
after_success:
  - .travis/maybe-publish-coverage.sh
after_deploy:
  - $(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: y+utmeKuYFtKh2in0d7HljQJxhX4tg+RejLD9FvQ11mlsYi20xUoXG8llY81/G0smETW2Sj8JYowFEImO/nURbWzcav1/jacUsqp2PemPKYHddONdAQ3ACwC9/3J4yRVEbJPaEZeHnfLfLxFnPtpgUALt+N7z8HWwBlSTfA+RdN069Hgit71lWPDts50ebYrBt+26dUFZMvv6HD6IPvTBLRSMJAsDhFKpJbgliY4rPEWLGfbHRpY3UyyrUVPhInsgaTbGnMANEeDauegNASr1MJTNGTvA+lhpbJeChWq40ZgztsVJFXM6U+JmI92hTIwDR16xSKmgeaexQAkrh/ULMkDlg4SWmv5togaCP+0MYEhyVYSk2Q6XgrgcyM6vQ8w5Ua+krlCt0JobSVx8MEOwvKXgrDRLJNWdVJiLjuyY0poHMd1q8fFP5sZ+VhiGkOtG68gFgybk/LB0NFyH8za1r2Kr79e//y/47TWcHphioHx5H9pOfMjB4Lh8SVOe1DybCiScVv02rCFQa4f3rNrhzIhVUpl5Bgo0W+rdBz6lteSNABtnTpD6PhocHjhrbe9ne7nFiyIrLn4FGzqLKHAAycBbwQ5Oo1O68LXjLG/n8/9+1EPmmG1lL7FupSnqGo9AAFcSfnfRixgkESS9SHXauXYH+KLuwywQ3oVXS4Ubqg=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: '8.1.2'
    tags: true
notifications:
  slack:
    secure: jOkCRCBQ14P7sL1kqrQl8LQ4Otz4eaWW1Utbj3djlpLclTGxxB/5qeb6t1bO1mAIZrs0rMQimAQJLOHzT5xKxl2M4ihkNOj0mSIp2j/S74obZ9Kgm5J2BkFiqXUDFXDOXrofXh/bFYgKJG1sT81EY3XY8covh+1WTPPbJGv+qyFfwpcQeSNC7qYNw5gJz6nLLOwP+3hoGxdTbJkzrwP+6vKAKR7LSjyJ/Iv/wS+Pw9UgRhk++nSMDrO5QpkQPt4JfmWlkB7FJauyMc5Qyjr6ClCj1KHwVHPJdkvhfwPjThr/8NMEsmNIlcsD8Xcpyx8jLqv5dRBAZlc1PQu8n3uAwnI5kCr4iQ41mMFox+T9+TnHKobMrcP4Ypl1FFj2kGQCVVNM1i1cCYPq3elCidIWLeVhmR7D0xAPbV8NcP7GSt9WlAzCkr0e1JzBpKT1idKCJuZfDLwfVh/jq2sMzDl3zYzAF9PPnINFWn1UxRvPnEK+W+NU2tGQyF0/sBismS52gEMCaHg87jlTgU5U/O9FO3dbKOnLZbQBqfMw6zt7+RJKvUlbPyRVRMsVklzadzQTjn1B9m+qDV5rSXk1rdqnlJrQFkcWPjosggoteeCAzkOy+LLeQCLWCLzIMMialGtsNJIxS7vQmEA/dSdqo4/hKdmykdvAjlNCMmAkovTkvBg=
